#! /usr/bin/env bash
MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export FLASK_DEBUG=False
export FLASK_RELOAD=False
source $MY_DIR/set-version.sh
source pyenv/bin/activate && python src/server.py

