#! /usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
case $1 in
    start)
        $DIR/start-server
    ;;
    stop)
        $DIR/stop-server
    ;;
    debug)
        $DIR/debug-server
    ;;
    *)
        echo "usage: server [start|stop|debug]";;
esac
