#! /usr/bin/env bash

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [ ! -n "$PORT" ]; then
    PORT=5000
fi
source $MY_DIR/set-version.sh
source .pyenv/bin/activate
gunicorn --bind 0.0.0.0:$PORT core:app

